#destination: ./_site
#auto:        false
#lsi: true
#server_port: 4000
pygments: true
#markdown:    maruku
markdown: rdiscount
#permalink:   date
exclude: [CNAME, README.md, public]
title: "m.igrs.jp"
url: "http://m.igrs.jp"

#tag_dir: tags
tag_title_prefix: "Tags &raquo; "
tag_exclude: [wakoopa]
related_tags: true

#category_dir: categories
category_title_prefix: "Categories &raquo; "

#content_delimeter: "<!-- -**-END-**- -->"
