#destination: ./_site
#auto:        false
#lsi:         false
#server_port: 4000
pygments:    true
#markdown:    maruku
#permalink:   date
exclude: [CNAME, README, public]
title: "m.igrs.jp"
url: "http://m.igrs.jp"
