title: m.igrs.jp
email: m@igrs.jp
#description: Don't eat the yellow snow
description: >-
  Dust In The Plain Text

baseurl: "/"
url: "https://m.igrs.jp"
twitter_username: migrs
github_username:  migrs

markdown: kramdown
#highlighter: pygments
logo: false
paginate: 10

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist

# Details for the RSS feed generator
author: 'Masato Igarashi'
permalink: /blog/:year/:month/:day/:title/
paginate_path: /blog/page/:num/
google_analytics: 'UA-655787-6'

feed:
  path: atom.xml

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .bundle
  - LICENSE.txt
